#!/usr/bin/env bash
# Configures /etc/hosts so localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8

sed -e '/localhost/d' -e '/facebook.com/d' /etc/hosts > /tmp/hosts_new
echo "127.0.0.2 localhost" >> /tmp/hosts_new
echo "8.8.8.8 facebook.com" >> /tmp/hosts_new
cat /tmp/hosts_new > /etc/hosts